import React, { useRef } from 'react';
import type { Engagement, EngagementControl, ControlFullDetail } from '../types';
import { CloseIcon } from './icons/Icons';
import { detailedControlData } from '../constants';

interface EngagementReportModalProps {
  engagement: Engagement;
  controls: EngagementControl[];
  onClose: () => void;
}

const EngagementReportModal: React.FC<EngagementReportModalProps> = ({
  engagement,
  controls,
  onClose,
}) => {
  const reportRef = useRef<HTMLDivElement>(null);

  const handleDownloadPDF = () => {
    const el = reportRef.current;
    if (!el) return;
    const w = window.open('', '_blank');
    if (!w) { alert('Allow pop-ups to download.'); return; }
    w.document.write(`<!DOCTYPE html><html><head><title>Engagement Report — ${engagement.name}</title>
      <style>
        @page { margin: 18mm; size: A4; }
        * { margin:0; padding:0; box-sizing:border-box; }
        body { font-family:'Segoe UI',system-ui,-apple-system,sans-serif; color:#1a1a2e; line-height:1.5; padding:24px; }
        .header { border-bottom:3px solid #4338ca; padding-bottom:14px; margin-bottom:20px; }
        .header h1 { font-size:22px; color:#1e1b4b; } .header p { font-size:11px; color:#6b7280; }
        .section { margin-bottom:20px; }
        .stitle { font-size:12px; font-weight:700; text-transform:uppercase; letter-spacing:.05em; color:#4338ca; border-bottom:1px solid #e5e7eb; padding-bottom:5px; margin-bottom:10px; }
        .grid2 { display:grid; grid-template-columns:150px 1fr; gap:4px 14px; font-size:12px; }
        .lbl { color:#6b7280; font-weight:500; } .val { color:#1f2937; font-weight:600; }
        table { width:100%; border-collapse:collapse; font-size:11px; margin-top:6px; }
        th { background:#f3f4f6; text-align:left; padding:7px 8px; font-weight:600; color:#374151; border:1px solid #e5e7eb; }
        td { padding:7px 8px; border:1px solid #e5e7eb; color:#4b5563; }
        tr:nth-child(even) td { background:#f9fafb; }
        .badge { display:inline-block; padding:2px 8px; border-radius:9999px; font-size:10px; font-weight:600; }
        .b-effective { background:#dcfce7; color:#166534; } .b-ineffective { background:#fee2e2; color:#991b1b; }
        .b-pending { background:#fce7f3; color:#9d174d; } .b-progress { background:#dbeafe; color:#1e40af; }
        .b-notstarted { background:#f3f4f6; color:#6b7280; } .b-concluded { background:#e5e7eb; color:#374151; }
        .summary-grid { display:grid; grid-template-columns:repeat(4,1fr); gap:10px; margin-top:8px; }
        .summary-card { text-align:center; padding:10px; border:1px solid #e5e7eb; border-radius:8px; }
        .summary-card .num { font-size:22px; font-weight:700; } .summary-card .lbl { font-size:10px; color:#6b7280; text-transform:uppercase; }
        .footer { margin-top:28px; padding-top:14px; border-top:1px solid #e5e7eb; font-size:10px; color:#9ca3af; text-align:center; }
      </style></head><body>${el.innerHTML}
      <div class="footer">Generated by Audit Management Platform — ${new Date().toLocaleString('en-GB', { day:'numeric', month:'short', year:'numeric', hour:'2-digit', minute:'2-digit' })}</div>
      </body></html>`);
    w.document.close();
    setTimeout(() => { w.print(); w.close(); }, 400);
  };

  const concluded = controls.filter(c => c.status === 'Concluded');
  const pendingReview = controls.filter(c => c.status === 'Pending Review');
  const inProgress = controls.filter(c => c.status === 'Evidence Collection' || c.status === 'Testing In Progress');
  const notStarted = controls.filter(c => c.status === 'Not Started');
  const totalExceptions = controls.reduce((s, c) => s + c.exceptions, 0);
  const effective = controls.filter(c => c.conclusion === 'Effective').length;
  const ineffective = controls.filter(c => c.conclusion === 'Ineffective').length;
  const isDraft = engagement.status !== 'CLOSED';

  const getStatusBadgeClass = (status: string) => {
    switch(status) {
      case 'Not Started': return 'b-notstarted';
      case 'Evidence Collection': case 'Testing In Progress': return 'b-progress';
      case 'Pending Review': return 'b-pending';
      case 'Concluded': return 'b-concluded';
      default: return 'b-notstarted';
    }
  };

  const getResultBadgeClass = (conclusion: string | null) => {
    if (conclusion === 'Effective') return 'b-effective';
    if (conclusion === 'Ineffective') return 'b-ineffective';
    return 'b-notstarted';
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-60">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-5xl max-h-[90vh] flex flex-col">
        <div className="flex items-center justify-between p-5 border-b border-gray-200">
          <div>
            <h2 className="text-lg font-bold text-gray-900">Engagement Report{isDraft ? ' (Draft)' : ''}</h2>
            <p className="text-sm text-gray-500">{engagement.name}</p>
          </div>
          <div className="flex items-center gap-3">
            <button onClick={handleDownloadPDF} className="rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500">
              Download PDF
            </button>
            <button onClick={onClose} className="p-1.5 text-gray-400 hover:text-gray-600 rounded-full hover:bg-gray-100">
              <CloseIcon className="h-5 w-5" />
            </button>
          </div>
        </div>

        <div className="flex-grow overflow-y-auto p-6 bg-gray-50">
          <div ref={reportRef} className="bg-white rounded-lg border border-gray-200 shadow-sm p-8 max-w-4xl mx-auto">
            {/* Header */}
            <div style={{ borderBottom: '3px solid #4338ca', paddingBottom: 14, marginBottom: 20 }}>
              <h1 style={{ fontSize: 22, fontWeight: 700, color: '#1e1b4b', marginBottom: 4 }}>
                Engagement Report{isDraft ? ' — DRAFT' : ''}
              </h1>
              <p style={{ fontSize: 11, color: '#6b7280' }}>
                {engagement.name} | Generated: {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}
              </p>
            </div>

            {/* Section 1: Engagement Info */}
            <div className="mb-6">
              <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-700 border-b border-gray-200 pb-1.5 mb-3">Section 1 — Engagement Information</h3>
              <div className="grid grid-cols-[150px_1fr] gap-x-4 gap-y-1.5 text-sm">
                <span className="text-gray-500 font-medium">Engagement</span>
                <span className="text-gray-900 font-semibold">{engagement.name}</span>
                <span className="text-gray-500 font-medium">Type</span>
                <span className="text-gray-900 font-semibold">{engagement.type}</span>
                <span className="text-gray-500 font-medium">Status</span>
                <span className="text-gray-900 font-semibold">{engagement.status}</span>
                <span className="text-gray-500 font-medium">Linked RACM</span>
                <span className="text-gray-900 font-semibold">{engagement.linkedRacmName || 'FY26 SOX v1.0'}</span>
                <span className="text-gray-500 font-medium">Period</span>
                <span className="text-gray-900 font-semibold">1 Apr 2025 – 31 Mar 2026</span>
              </div>
            </div>

            {/* Section 2: Status Summary */}
            <div className="mb-6">
              <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-700 border-b border-gray-200 pb-1.5 mb-3">Section 2 — Status Summary</h3>
              <div className="grid grid-cols-4 gap-3">
                {[
                  { label: 'Not Started', value: notStarted.length, color: 'text-gray-600' },
                  { label: 'In Progress', value: inProgress.length, color: 'text-blue-700' },
                  { label: 'Pending Review', value: pendingReview.length, color: 'text-pink-700' },
                  { label: 'Concluded', value: concluded.length, color: 'text-gray-800' },
                ].map(s => (
                  <div key={s.label} className="text-center p-3 border border-gray-200 rounded-lg">
                    <div className={`text-2xl font-bold ${s.color}`}>{s.value}</div>
                    <div className="text-[10px] uppercase text-gray-500 font-medium">{s.label}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* Section 3: Control List */}
            <div className="mb-6">
              <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-700 border-b border-gray-200 pb-1.5 mb-3">Section 3 — Control Testing Summary</h3>
              <div className="overflow-x-auto">
                <table className="min-w-full text-xs border border-gray-200">
                  <thead>
                    <tr className="bg-gray-50">
                      <th className="text-left px-2.5 py-2 font-semibold text-gray-700 border border-gray-200">Control ID</th>
                      <th className="text-left px-2.5 py-2 font-semibold text-gray-700 border border-gray-200">Control Name</th>
                      <th className="text-left px-2.5 py-2 font-semibold text-gray-700 border border-gray-200">Key</th>
                      <th className="text-left px-2.5 py-2 font-semibold text-gray-700 border border-gray-200">Status</th>
                      <th className="text-left px-2.5 py-2 font-semibold text-gray-700 border border-gray-200">Samples</th>
                      <th className="text-left px-2.5 py-2 font-semibold text-gray-700 border border-gray-200">Exceptions</th>
                      <th className="text-left px-2.5 py-2 font-semibold text-gray-700 border border-gray-200">Result</th>
                    </tr>
                  </thead>
                  <tbody>
                    {controls.map((c, i) => (
                      <tr key={c.id} className={i % 2 === 1 ? 'bg-gray-50' : ''}>
                        <td className="px-2.5 py-2 border border-gray-200 font-medium text-gray-800">{c.controlId}</td>
                        <td className="px-2.5 py-2 border border-gray-200 text-gray-700">{c.controlName}</td>
                        <td className="px-2.5 py-2 border border-gray-200 text-center font-semibold">{c.key ? 'Y' : 'N'}</td>
                        <td className="px-2.5 py-2 border border-gray-200">
                          <span className={`inline-block px-2 py-0.5 rounded-full text-[10px] font-semibold ${
                            c.status === 'Concluded' ? 'bg-gray-200 text-gray-800' :
                            c.status === 'Pending Review' ? 'bg-pink-100 text-pink-800' :
                            c.status === 'Not Started' ? 'bg-gray-100 text-gray-600' :
                            'bg-blue-100 text-blue-800'
                          }`}>{c.status}</span>
                        </td>
                        <td className="px-2.5 py-2 border border-gray-200 text-center">{c.testedSamples}/{c.totalSamples}</td>
                        <td className="px-2.5 py-2 border border-gray-200 text-center font-semibold" style={{ color: c.exceptions > 0 ? '#dc2626' : undefined }}>{c.exceptions > 0 ? c.exceptions : '—'}</td>
                        <td className="px-2.5 py-2 border border-gray-200">
                          {c.conclusion ? (
                            <span className={`inline-block px-2 py-0.5 rounded-full text-[10px] font-semibold ${c.conclusion === 'Effective' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>{c.conclusion}</span>
                          ) : c.status === 'Pending Review' ? (
                            <span className="text-[10px] text-pink-600 font-medium">Pending Review</span>
                          ) : (
                            <span className="text-gray-400">—</span>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Section 4: Exceptions */}
            <div className="mb-6">
              <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-700 border-b border-gray-200 pb-1.5 mb-3">Section 4 — Exception Summary</h3>
              <div className="grid grid-cols-3 gap-3">
                <div className="text-center p-3 border border-gray-200 rounded-lg">
                  <div className="text-2xl font-bold text-gray-900">{controls.length}</div>
                  <div className="text-[10px] uppercase text-gray-500 font-medium">Total Controls</div>
                </div>
                <div className="text-center p-3 border border-red-200 rounded-lg bg-red-50">
                  <div className="text-2xl font-bold text-red-700">{totalExceptions}</div>
                  <div className="text-[10px] uppercase text-red-600 font-medium">Total Exceptions</div>
                </div>
                <div className="text-center p-3 border border-red-200 rounded-lg bg-red-50">
                  <div className="text-2xl font-bold text-red-700">{ineffective}</div>
                  <div className="text-[10px] uppercase text-red-600 font-medium">Ineffective Controls</div>
                </div>
              </div>
            </div>

            {/* Section 5: Engagement Result */}
            <div className="mb-2">
              <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-700 border-b border-gray-200 pb-1.5 mb-3">Section 5 — Overall Engagement Result</h3>
              <div className="grid grid-cols-2 gap-3 mb-4">
                <div className="text-center p-3 border border-green-200 rounded-lg bg-green-50">
                  <div className="text-2xl font-bold text-green-700">{effective}</div>
                  <div className="text-[10px] uppercase text-green-600 font-medium">Effective Controls</div>
                </div>
                <div className="text-center p-3 border border-red-200 rounded-lg bg-red-50">
                  <div className="text-2xl font-bold text-red-700">{ineffective}</div>
                  <div className="text-[10px] uppercase text-red-600 font-medium">Ineffective Controls</div>
                </div>
              </div>
              <div className="text-center p-5 border-2 border-gray-200 rounded-lg">
                <p className="text-xs uppercase text-gray-500 font-medium mb-2">Engagement Completion</p>
                <span className={`inline-block px-4 py-1.5 rounded-full text-sm font-bold ${
                  concluded.length === controls.length ? 'bg-green-100 text-green-800' : 'bg-amber-100 text-amber-800'
                }`}>
                  {concluded.length === controls.length ? 'All Controls Concluded' : `${concluded.length} of ${controls.length} Controls Concluded`}
                </span>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
};

export default EngagementReportModal;
