import React, { useRef } from 'react';
import type { ControlFullDetail, EvidenceModel, SampleFinalStatus, TestScriptRule, RuleExecutionResult } from '../types';
import { CloseIcon } from './icons/Icons';

interface SampleDetailReportModalProps {
  controlId: string;
  controlName: string;
  sample: Record<string, any>;
  sampleIndex: number;
  evidence: EvidenceModel[];
  sampleStatus: SampleFinalStatus;
  systemDeterminedResult: string;
  attributes: { id: number; name: string }[];
  onClose: () => void;
}

const SampleDetailReportModal: React.FC<SampleDetailReportModalProps> = ({
  controlId,
  controlName,
  sample,
  sampleIndex,
  evidence,
  sampleStatus,
  systemDeterminedResult,
  attributes,
  onClose,
}) => {
  const reportRef = useRef<HTMLDivElement>(null);

  const handleDownloadPDF = () => {
    const el = reportRef.current;
    if (!el) return;
    const w = window.open('', '_blank');
    if (!w) { alert('Allow pop-ups to download.'); return; }
    w.document.write(`<!DOCTYPE html><html><head><title>Sample Report — ${sample.sampleId}</title>
      <style>
        @page { margin: 20mm; size: A4; }
        * { margin:0; padding:0; box-sizing:border-box; }
        body { font-family:'Segoe UI',system-ui,-apple-system,sans-serif; color:#1a1a2e; line-height:1.5; padding:24px; }
        .header { border-bottom:3px solid #4338ca; padding-bottom:14px; margin-bottom:20px; }
        .header h1 { font-size:18px; color:#1e1b4b; } .header p { font-size:11px; color:#6b7280; }
        .section { margin-bottom:18px; }
        .stitle { font-size:12px; font-weight:700; text-transform:uppercase; letter-spacing:.05em; color:#4338ca; border-bottom:1px solid #e5e7eb; padding-bottom:5px; margin-bottom:10px; }
        .grid2 { display:grid; grid-template-columns:150px 1fr; gap:4px 14px; font-size:12px; }
        .lbl { color:#6b7280; font-weight:500; } .val { color:#1f2937; font-weight:600; }
        table { width:100%; border-collapse:collapse; font-size:11px; margin-top:6px; }
        th { background:#f3f4f6; text-align:left; padding:7px 8px; font-weight:600; color:#374151; border:1px solid #e5e7eb; }
        td { padding:7px 8px; border:1px solid #e5e7eb; color:#4b5563; }
        tr:nth-child(even) td { background:#f9fafb; }
        .badge { display:inline-block; padding:2px 8px; border-radius:9999px; font-size:10px; font-weight:600; }
        .b-pass { background:#dcfce7; color:#166534; } .b-fail { background:#fee2e2; color:#991b1b; } .b-nt { background:#f3f4f6; color:#6b7280; }
        .footer { margin-top:24px; padding-top:12px; border-top:1px solid #e5e7eb; font-size:10px; color:#9ca3af; text-align:center; }
      </style></head><body>${el.innerHTML}
      <div class="footer">Generated by Audit Management Platform — ${new Date().toLocaleString('en-GB', { day:'numeric', month:'short', year:'numeric', hour:'2-digit', minute:'2-digit' })}</div>
      </body></html>`);
    w.document.close();
    setTimeout(() => { w.print(); w.close(); }, 400);
  };

  const recordData = sample.recordData || {};
  const hasRecordData = Object.keys(recordData).length > 0;
  const uploadedEvidence = evidence.filter(ev => !!ev.fileName);
  const missingEvidence = evidence.filter(ev => !ev.fileName);

  const getResultLabel = (status: SampleFinalStatus) => {
    switch (status) {
      case 'PASS': return 'Pass';
      case 'FAIL': return 'Fail';
      case 'OVERRIDDEN': return 'Override (Pass)';
      case 'NOT_APPLICABLE': return 'N/A';
      default: return 'Not Tested';
    }
  };

  const getResultClass = (status: SampleFinalStatus) => {
    switch (status) {
      case 'PASS': case 'OVERRIDDEN': return 'bg-green-100 text-green-800';
      case 'FAIL': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-600';
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-60">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-3xl max-h-[90vh] flex flex-col">
        <div className="flex items-center justify-between p-5 border-b border-gray-200">
          <div>
            <h2 className="text-lg font-bold text-gray-900">Sample Detail Report</h2>
            <p className="text-sm text-gray-500">Sample {sampleIndex + 1} — {sample.sampleId}</p>
          </div>
          <div className="flex items-center gap-3">
            <button onClick={handleDownloadPDF} className="rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500">
              Download PDF
            </button>
            <button onClick={onClose} className="p-1.5 text-gray-400 hover:text-gray-600 rounded-full hover:bg-gray-100">
              <CloseIcon className="h-5 w-5" />
            </button>
          </div>
        </div>

        <div className="flex-grow overflow-y-auto p-6 bg-gray-50">
          <div ref={reportRef} className="bg-white rounded-lg border border-gray-200 shadow-sm p-8 max-w-2xl mx-auto">
            {/* Header */}
            <div style={{ borderBottom: '3px solid #4338ca', paddingBottom: 14, marginBottom: 20 }}>
              <h1 style={{ fontSize: 18, fontWeight: 700, color: '#1e1b4b', marginBottom: 4 }}>
                Sample Detail Report
              </h1>
              <p style={{ fontSize: 11, color: '#6b7280' }}>
                {controlId} — {controlName} | Sample {sampleIndex + 1} ({sample.sampleId}) | {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}
              </p>
            </div>

            {/* Section 1: Sample Information */}
            <div className="mb-6">
              <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-700 border-b border-gray-200 pb-1.5 mb-3">Section 1 — Sample Information</h3>
              <div className="grid grid-cols-[140px_1fr] gap-x-4 gap-y-1.5 text-sm">
                <span className="text-gray-500 font-medium">Sample ID</span>
                <span className="text-gray-900 font-semibold">{sample.sampleId}</span>
                <span className="text-gray-500 font-medium">Control ID</span>
                <span className="text-gray-900 font-semibold">{controlId}</span>
                <span className="text-gray-500 font-medium">Control Name</span>
                <span className="text-gray-900 font-semibold">{controlName}</span>
              </div>
            </div>

            {/* Section 2: Sample Data Fields */}
            {hasRecordData && (
              <div className="mb-6">
                <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-700 border-b border-gray-200 pb-1.5 mb-3">Section 2 — Sample Data Fields</h3>
                <table className="min-w-full text-xs border border-gray-200">
                  <thead>
                    <tr className="bg-gray-50">
                      <th className="text-left px-3 py-2 font-semibold text-gray-700 border border-gray-200">Field</th>
                      <th className="text-left px-3 py-2 font-semibold text-gray-700 border border-gray-200">Value</th>
                    </tr>
                  </thead>
                  <tbody>
                    {Object.entries(recordData).map(([key, value], i) => (
                      <tr key={key} className={i % 2 === 1 ? 'bg-gray-50' : ''}>
                        <td className="px-3 py-2 border border-gray-200 text-gray-600 font-medium capitalize">{key.replace(/([A-Z])/g, ' $1')}</td>
                        <td className="px-3 py-2 border border-gray-200 text-gray-800 font-semibold">{String(value ?? 'null')}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            {/* Section 3: Evidence Attached */}
            <div className="mb-6">
              <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-700 border-b border-gray-200 pb-1.5 mb-3">Section {hasRecordData ? '3' : '2'} — Evidence Attached</h3>
              <table className="min-w-full text-xs border border-gray-200">
                <thead>
                  <tr className="bg-gray-50">
                    <th className="text-left px-3 py-2 font-semibold text-gray-700 border border-gray-200">Evidence Type</th>
                    <th className="text-left px-3 py-2 font-semibold text-gray-700 border border-gray-200">Filename</th>
                    <th className="text-left px-3 py-2 font-semibold text-gray-700 border border-gray-200">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {evidence.map((ev, i) => (
                    <tr key={ev.evidenceId} className={i % 2 === 1 ? 'bg-gray-50' : ''}>
                      <td className="px-3 py-2 border border-gray-200 font-medium text-gray-800">{ev.evidenceType}</td>
                      <td className="px-3 py-2 border border-gray-200 text-gray-600">{ev.fileName || '—'}</td>
                      <td className="px-3 py-2 border border-gray-200">
                        <span className={`inline-block px-2 py-0.5 rounded-full text-[10px] font-semibold ${ev.fileName ? 'bg-green-100 text-green-800' : 'bg-amber-100 text-amber-800'}`}>
                          {ev.fileName ? 'Uploaded' : 'Missing'}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
              <p className="text-xs text-gray-500 mt-2">{uploadedEvidence.length} of {evidence.length} evidence items uploaded</p>
            </div>

            {/* Section 4: Attribute-level results */}
            {attributes.length > 0 && (
              <div className="mb-6">
                <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-700 border-b border-gray-200 pb-1.5 mb-3">Section {hasRecordData ? '4' : '3'} — Attributes Tested</h3>
                <table className="min-w-full text-xs border border-gray-200">
                  <thead>
                    <tr className="bg-gray-50">
                      <th className="text-left px-3 py-2 font-semibold text-gray-700 border border-gray-200 w-10">#</th>
                      <th className="text-left px-3 py-2 font-semibold text-gray-700 border border-gray-200">Attribute</th>
                    </tr>
                  </thead>
                  <tbody>
                    {attributes.map((attr, i) => (
                      <tr key={attr.evidenceId} className={i % 2 === 1 ? 'bg-gray-50' : ''}>
                        <td className="px-3 py-2 border border-gray-200 text-gray-500 font-medium">{String.fromCharCode(65 + i)}</td>
                        <td className="px-3 py-2 border border-gray-200 text-gray-800">{attr.name}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            {/* Section 5: Sample Result */}
            <div className="mb-2">
              <h3 className="text-xs font-bold uppercase tracking-wider text-indigo-700 border-b border-gray-200 pb-1.5 mb-3">Sample Result</h3>
              <div className="text-center p-5 border-2 border-gray-200 rounded-lg">
                <p className="text-xs uppercase text-gray-500 font-medium mb-2">Sample Testing Result</p>
                <span className={`inline-block px-4 py-1.5 rounded-full text-sm font-bold ${getResultClass(sampleStatus)}`}>
                  {getResultLabel(sampleStatus)}
                </span>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
};

export default SampleDetailReportModal;
